base/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView

import core
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name="main"),
    path('list/', ListView.as_view(template_name='location/list.html', model=core.models.Location), name='list'),
    path('<slug:slug>/', DetailView.as_view(
        template_name='location/detail.html',model=core.models.Location), name='detail'),

]

location/urls.py
from django.urls import path, include

from . import views

app_name = 'location'
urlpatterns = [

    path('add/', views.AddLocationView.as_view(), name='add'),
    path('edit/<slug:slug>/', views.UpdateLocation.as_view(), name='edit'),
    path('delete/<slug:slug>/', views.DeleteLocation.as_view(), name='delete'),

]

users/urls.py
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LogoutView
)
from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from . import views

app_name = 'users'
urlpatterns = [
    path(_('login/'), views.UserLoginView.as_view(), name='login'),
    path(_('logout/'), LogoutView.as_view(next_page=reverse_lazy('base:main')), name='logout'),
    path('activate/<str:uidb64>/<str:token>', views.activate, name='activate'),
    path(_('registrationConfirmed/'),
         TemplateView.as_view(template_name='users/registration/reg_confirmed.html'),
         name='registrationConfirmed'),
    path(_('profile/'), views.Profile.as_view(), name='profile'),
    path(_('register/'), views.UserRegistration.as_view(), name="register"),
    path(_('passwordChange/'), views.ChangePasswordView.as_view(), name="password_change"),
    path(_('passwordChangeDone/'),
         PasswordChangeDoneView.as_view(template_name='users/registration/password_change_done.html'),
         name="password_change_done"
         ),

    path(_('passwordReset'),
         PasswordResetView.as_view(
             template_name='users/registration/password_reset_form.html',
             email_template_name='users/registration/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path(
        _('passwordResetDone'),
        PasswordResetView.as_view(template_name='users/registration/password_reset_done.html'),
        name='password_reset_done'),
    path('passwordResetConfirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/registration/password_reset_confirm_form.html',
             success_url=reverse_lazy('users:password_reset_complete')
         ),
         name='password_reset_confirm'
         ),
    path('passwordResetComplete',
         PasswordResetCompleteView.as_view(
             template_name='users/registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

location/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponse
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, DeleteView

import core.models
from core.views import PassRequestToFormViewMixin


# Create your views here.
class AddLocationView(LoginRequiredMixin, PassRequestToFormViewMixin, CreateView):
    template_name = 'location/add_location.html'
    model = core.models.Location
    success_url = reverse_lazy('base:list')
    form_class = core.forms.LocationForm

    def form_valid(self, form):
        my_user = self.request.user
        if not core.models.Location.objects.filter(user=my_user).count() >= my_user.locations:
            form.instance.user = my_user
            form.instance.slug = slugify(form.instance.name)
            return super().form_valid(form)
        else:
            return HttpResponse('nu se poate')
            # raise ValueError('%s has already a  locations' % my_user)


class UpdateLocation(LoginRequiredMixin, UpdateView):
    model = core.models.Location
    fields = (
        'description', 'image', 'country', 'region', 'province',
        'city', 'zip_code', 'street_name', 'street_number')
    template_name = 'location/edit_location.html'
    success_url = reverse_lazy('base:list')


class DeleteLocation(LoginRequiredMixin, DeleteView):
    template_name = 'location/delete_location.html'
    success_url = reverse_lazy('base:list')
    model = core.models.Location

location/templates/location/add_location.html
{% extends 'base/base.html' %}
{% block title %}
location for {{ user }}
{% endblock %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        {{ form }}
        <input type="submit" value="add location">
    </form>

{% endblock %}

location/templates/location/delete_location.html
{% extends 'base/base.html' %}
{% block title %}
location for {{ user }}
{% endblock %}
{% block content %}
    confirm delete location "{{ object }}"
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form }}
        <input type="submit" value="delete">
    </form>
    <a href="{%  url 'users:profile' %}">cancel</a>
{% endblock %}

location/templates/location/detail.html
{% include 'base/base.html' %}
{% load static %}
{% block title %}

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            {{ object.name }}<br>
        </div>
        <div class="col-md-6">
            {% for zi,orari in object.get_orari.items %}
                {{ zi }}
                {% for foo in orari %}
                    <b>{{ foo.start }} - {{ foo.fine }}</b> <b> | </b>
                {% endfor %}
                <br>
            {% endfor %}
        </div>
        <div class="col-md-6">
            {{ object.country }}<br>
    {{ object.region }}<br>
    {{ object.province }}<br>
    {{ object.city }}<br>
    {{ object.sip_code }}<br>
    {{ object.street_name }}<br>
    {{ object.street_number }}<br>
        </div>
        <div class="col-12">
            <img src="{{ object.image.url }}" class="img-fluid">
        </div>
        <div class="col-12">
            {{ object.description }}<br>
        </div>
    </div>





    <br>

{% endblock %}

location/templates/location/edit_location.html
{% extends 'base/base.html' %}
{% block title %}
update for {{ user }}
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form }}
        <input type="submit" value="update">
    </form>

{% endblock %}

location/templates/location/list.html
{% include 'base/base.html' %}
{% block title %}

{% endblock %}

{% block content %}
    locations
    {% for object in object_list %}
        <a href="{% url 'base:detail' object.slug %}">{{ object }}</a>
     <br>
    {% endfor %}
{% endblock %}