base/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView

import core
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name="main"),
    path('list/', ListView.as_view(template_name='location/list.html', model=core.models.Location), name='list'),
    path('<slug:slug>/', DetailView.as_view(
        template_name='location/detail.html',model=core.models.Location), name='detail'),

]

orari/urls.py
from django.urls import path, include
from . import views
app_name='orari'
urlpatterns = [
    path('update/<int:pk>/', views.UpdateOrari.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteOrario.as_view(), name='delete'),
    path('<slug:slug>/', views.CreateOrarioView.as_view(), name="add_orario"),
    path('<slug:slug>/dash/', views.ListOrariForEdit.as_view(), name="dash_orario"),
    path('<slug:slug>/<int:weekday>/', views.CreateOrarioView.as_view(), name="add_orario"),


]

orari/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponse, get_object_or_404, Http404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from core.forms import OrariForm
import core.models
from core.views import PassRequestToFormViewMixin

class CreateOrarioView(LoginRequiredMixin, PassRequestToFormViewMixin,CreateView):
    template_name = 'orari/add.html'
    success_url = reverse_lazy('orari:dash_orario')
    model = core.models.Orari
    form_class = core.forms.OrariForm

    def get_initial(self):
        location = get_object_or_404(core.models.Location, slug=self.kwargs.get('slug'))

        weekday = 0
        if 'weekday' in self.kwargs.keys():
            day = self.kwargs.get('weekday')
            if day in range(7):
                weekday = day
        return {'location': location, 'weekday': weekday, 'stars': '09:00'}

    def get_success_url(self):
        return reverse_lazy('orari:dash_orario',args=[self.kwargs.get('slug')])

    def dispatch(self, request, *args, **kwargs):
        loc = get_object_or_404(core.models.Location, slug=self.kwargs.get('slug'))
        if loc.user == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return redirect(reverse_lazy('users:profile'))
        raise Http404
class UpdateOrari(LoginRequiredMixin, UpdateView):
    template_name = 'orari/add.html'
    success_url = reverse_lazy('users:profile')
    model = core.models.Orari
    fields = ('start', 'fine')

    def dispatch(self, request, *args, **kwargs):
        orar = get_object_or_404(core.models.Orari, id=kwargs.get('pk'))
        if orar.location.user == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return redirect(reverse_lazy('users:profile'))
        raise Http404

    def get_success_url(self):
        orar = get_object_or_404(core.models.Orari, id=self.kwargs.get('pk'))
        return reverse_lazy('orari:dash_orario', args=[orar.location.slug])

class ListOrariForEdit(LoginRequiredMixin,ListView):
    template_name = 'orari/dash.html'
    model = core.models.Orari
    context_object_name = 'orari'
    def get_queryset(self):
        location=get_object_or_404(core.models.Location, slug=self.kwargs.get('slug'))
        return location.location_schedule.order_by('weekday', 'start')
    def dispatch(self, request, *args, **kwargs):
        location = get_object_or_404(core.models.Location, slug=kwargs.get('slug'))
        if location.user == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return redirect(reverse_lazy('users:profile'))
        raise Http404
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        location = get_object_or_404(core.models.Location, slug=self.kwargs.get('slug'))

        context['location'] = location
        return context


class DeleteOrario(LoginRequiredMixin, DeleteView):
    template_name = 'orari/delete.html'
    model = core.models.Orari

    def get_success_url(self):
        orar = get_object_or_404(core.models.Orari, id=self.kwargs.get('pk'))
        return reverse_lazy('orari:dash_orario', args=[orar.location.slug])

orari/templates/orari/add.html
{% extends 'base/base.html' %}
{% block title %}
location for {{ user }}
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form }}
        <input type="submit" value="add orario">
    </form>

{% endblock %}

orari/templates/orari/dash.html
{% extends 'base/base.html' %}
{% block title %}
location for {{ user }}
{% endblock %}
{% block content %}
    {{ location }}<br>
    {% for zi,orari in location.get_orari.items %}
        {{ zi }}
        {% for foo in orari %}
           <b>{{ foo.start }} - {{ foo.fine }}</b>
            <span> <a href="{% url 'orari:update' foo.pk %}">Edit</a></span>
            <span> <a href="{% url 'orari:delete' foo.pk %}">Delete</a></span>
            <b> | </b>
        {% endfor %}
        <a href="{% url 'orari:add_orario' location.slug  forloop.counter0 %}">+</a>
        <br>

    {% endfor %}


{% endblock %}

orari/templates/orari/delete.html
{% extends 'base/base.html' %}
{% block title %}
location for {{ user }}
{% endblock %}
{% block content %}
    confirm delete location "{{ object }}"
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form }}
        <input type="submit" value="delete">
    </form>
    <a href="{% url 'orari:dash_orario' object.location %}">cancel</a>

{% endblock %}

orari/templates/orari/update.html
{% extends 'base/base.html' %}
{% block title %}
location for {{ user }}
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form }}
        <input type="submit" value="add location">
    </form>

{% endblock %}