base/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView

import core
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name="main"),
    path('list/', ListView.as_view(template_name='location/list.html', model=core.models.Location), name='list'),
    path('<slug:slug>/', DetailView.as_view(
        template_name='location/detail.html',model=core.models.Location), name='detail'),

]

users/urls.py
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LogoutView
)
from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from . import views

app_name = 'users'
urlpatterns = [
    path(_('login/'), views.UserLoginView.as_view(), name='login'),
    path(_('logout/'), LogoutView.as_view(next_page=reverse_lazy('base:main')), name='logout'),
    path('activate/<str:uidb64>/<str:token>', views.activate, name='activate'),
    path(_('registrationConfirmed/'),
         TemplateView.as_view(template_name='users/registration/reg_confirmed.html'),
         name='registrationConfirmed'),
    path(_('profile/'), views.Profile.as_view(), name='profile'),
    path(_('register/'), views.UserRegistration.as_view(), name="register"),
    path(_('passwordChange/'), views.ChangePasswordView.as_view(), name="password_change"),
    path(_('passwordChangeDone/'),
         PasswordChangeDoneView.as_view(template_name='users/registration/password_change_done.html'),
         name="password_change_done"
         ),

    path(_('passwordReset'),
         PasswordResetView.as_view(
             template_name='users/registration/password_reset_form.html',
             email_template_name='users/registration/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path(
        _('passwordResetDone'),
        PasswordResetView.as_view(template_name='users/registration/password_reset_done.html'),
        name='password_reset_done'),
    path('passwordResetConfirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/registration/password_reset_confirm_form.html',
             success_url=reverse_lazy('users:password_reset_complete')
         ),
         name='password_reset_confirm'
         ),
    path('passwordResetComplete',
         PasswordResetCompleteView.as_view(
             template_name='users/registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

base/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    # if request.user.is_authenticated:
    #     return redirect(reverse_lazy('users:profile'))
    return render(request, 'main/index.html')

base/templates/base/base.html
{% extends 'base/base_main.html' %}
{% block nav %}
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}">Exit</a>
            <a href="{% url 'users:profile' %}">Profile</a>

            {% else %}
            <li>
                <a href="{% url 'users:login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'users:register' %}">Register</a>
            </li>
        {% endif %}



{% endblock %}

base/templates/base/base_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ request.site.domain }}
        {% endblock %}
    </title>
    {% block extra_css %}

    {% endblock %}
</head>
<body>
<nav>
    <ul style="list-style: none;flex-direction: row;">
        <li>
            <a href="{% url 'base:main' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}">Exit</a>
            <a href="{% url 'users:profile' %}">Profile</a>

            {% else %}
            <li>
                <a href="{% url 'users:login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'users:register' %}">Register</a>
            </li>
        {% endif %}

    </ul>
</nav>

{% block content %}

{% endblock %}
{% block extra_js %}

{% endblock %}
</body>
</html>